@startuml
skinparam defaultFontName "Noto Sans"
 
participant "Things\n(fe80::2222)" as Thing 
participant "Directory\n(fe80::1111)" as Directory 
participant Consumer

group Register phase:\na) The directory discovers Things\n    and retireves TDs from each device
    group Thing discovery
        Directory --> Thing : mDNS query\n"PTR _device._sub._wot._tcp.local"
        Thing -> Directory  : mDNS resp.\n"PTR lamp._device._sub._wot._tcp.local"
        Directory --> Thing : mDNS query\n"ANY lamp._device._sub._wot._tcp.local"
        Thing -> Directory  : mDNS resp.\n"SRV 1 0 10080 lamp.local"\n"TXT retrieve=/Things"
    end
    group Register to directory
        Directory --> Thing : mDNS query\n"AAAA lamp.local"
        Thing -> Directory  : mDNS resp.\n"AAAA fe80::2222"
        Directory -> Thing  : GET http://lamp.local/Things
        Thing -> Directory  : Thing Description: {"@context":...}
    end
end 
group Register phase:\nb) Things discover the directory\n   and register TDs by themselves
    group Thing directory discovery
        Thing --> Directory : mDNS query\n"PTR _directory._sub._wot._tcp.local"
        Directory -> Thing  : mDNS resp.\n"PTR mongo._directory._sub._wot._tcp.local"
        Thing --> Directory : mDNS query\n"ANY mongo._directory._sub.wot._tcp.local"
        Directory -> Thing  : mDNS resp.\n"SRV 1 0 80 tdir-mongo.local"\n"TXT retrieve=/Things register=/Things/register"
    end
    group Register to directory
        Thing --> Directory : mDNS query\n"AAAA tdir-mongo.local"
        Directory -> Thing  : mDNS resp.\n"AAAA fe80::1111"
        Thing -> Directory  : POST http://tdir-mongo.local/Things/register\n(payload: Thing Description)
        Directory -> Thing  : 201 Created
    end
end
group Consume phase:
    group Thing directory discovery
        Consumer --> Directory : mDNS query\n"PTR _directory._sub._wot._tcp.local"
        Directory -> Consumer  : mDNS resp.\n"PTR mongo._directory._sub._wot._tcp.local"
        Consumer --> Directory : mDNS query\n"ANY mongo._directory._sub.wot._tcp.local"
        Directory -> Consumer  : mDNS resp.\n"SRV 1 0 80 tdir-mongo.local"\n"TXT retrieve=/Things register=/Things/register"
    end
    group Query to directory
        Consumer --> Directory : mDNS query\n"AAAA tdir-mongo.local"
        Directory -> Consumer  : mDNS resp.\n"AAAA fe80::1111"
        Consumer -> Directory  : GET http://tdir-mongo.local/Things
        Directory -> Consumer  : ["lamp","otherThing1",...]
        Consumer -> Directory  : GET http://tdir-mongo.local/Things/lamp
        Directory -> Consumer  : Thing Description: {"@context":...}
    end
    group Interact with the Thing
        Consumer -> Thing      : mDNS query\n"AAAA lamp.local"
        Thing -> Consumer      : mDNS resp.\n"AAAA fe80::2222"
        Consumer -> Thing      : POST https://lamp.local/on
        Thing -> Consumer      : 200 OK
    end
end
@enduml