@startuml
hide members
class "td:Thing"

class "discovery:RegistrationInformation" {
  schema:dateCreated : xsd:datetime
  schema:dateModified : xsd:datetime
  schema:expires : xsd:datetime
}


note left of "td:Thing" 
  Thing Description (TD)
end note


"td:Thing" --> "discovery:RegistrationInformation" : "discovery:hasRegistrationInformation"


"discovery:LinkDescription" --|> "td:Thing"
"discovery:DirectoryDescription" --|> "td:Thing"

show "discovery:RegistrationInformation" attributes
note "Prefixes:\n\tdiscovery: https://www.w3.org/2021/wot/discovery#\n\ttd: https://www.w3.org/2019/wot/td#\n\tschema: http://schema.org/" as N1
@enduml
