@startuml
hide members
class "td:Thing"

class "discovery:RegistrationInformation" {
  dct:created : xsd:datetime
  dct:modified : xsd:datetime
  schema:expires : xsd:datetime
}


note left of "td:Thing" 
  Thing Description (TD)
end note


"td:Thing" --> "discovery:RegistrationInformation" : "discovery:hasRegistrationInformation"


"discovery:LinkDescription" --|> "td:Thing"
"discovery:DirectoryDescription" --|> "td:Thing"

show "discovery:RegistrationInformation" attributes
@enduml
