@startuml
hide members
class "td:Thing"

class "discovery:ThingEnriched" {
  schema:dateCreated : xsd:datetime
  schema:dateModified : xsd:datetime
  schema:expires : xsd:datetime
  discovery:ttl : xsd:integer
  discovery:retrieved : xsd:datetime
}

note left of "td:Thing" 
  Thing Description (TD)
end note

"discovery:ThingEnriched" --|> "td:Thing"
"discovery:ThingLink" --|> "discovery:ThingEnriched"
"discovery:ThingDirectory" --|> "discovery:ThingEnriched"

show "discovery:ThingEnriched" attributes
note "Prefixes:\n\tdiscovery: https://www.w3.org/2021/wot/discovery#\n\ttd: https://www.w3.org/2019/wot/td#\n\tschema: http://schema.org/" as N1
@enduml
