@startuml
hide members
class Thing as "td:Thing"
class ThingDirectory as "discovery:ThingDirectory"
class ThingLink as "discovery:ThingLink"

class RegInfo as "discovery:RegistrationInformation" #Azure {
  discovery:created : xsd:datetime
  discovery:modified : xsd:datetime
  discovery:expires : xsd:datetime
  discovery:ttl : xsd:integer
  discovery:retrieved : xsd:datetime
}
show RegInfo attributes

note left of Thing
  Thing Description (TD)
end note

Thing <|-- ThingDirectory
Thing <|-- ThingLink
Thing --> RegInfo : "discovery:hasRegistrationInformation"

note as Prefixes
Prefixes:
  td: https://www.w3.org/2019/wot/td#
  discovery: https://www.w3.org/2021/wot/discovery#
end note
@enduml
