@startuml exploration-class-diagram
/' global configurations '/
hide methods
hide members

class Thing <<service>>
together {
    class SelfDesc as "Self-describing Thing" <<service>>
    class Directory <<service>>
}

class TD as "td:Thing"
note right: Thing Description (TD)
together {
    class DD as "discovery:DirectoryDescription"
    ' note bottom: TD that describes\na Directory

    class LD as "discovery:LinkDescription"
    ' note bottom: TD that describes\na reference to another TD
}

/' relations '/
Thing <|-- SelfDesc
Thing <|-- Directory
SelfDesc "1" o-- "0..1  " TD: provides
TD <|-- DD
TD <|-- LD
Directory "1" o-- "0..*" TD: contains


@enduml