@startuml
hide members
class "td:Thing"
class "dsv:ThingPage" {
  dsv:hasCollectionSize : xsd:int
  dsv:hasPageSize : xsd:int
}
class "dsv:LinkDescription"
class "dsv:DirectoryDescription"
class "dsv:RegistrationInformation" {
  dc:created : xsd:datetime
  dc:modified : xsd:datetime
}

"dsv:ThingPage" <-- "dsv:ThingPage" : "dsv:hasNextPage"
"td:Thing" <-- "dsv:ThingPage" : "dsv:hasElements"
"td:Thing" --> "dsv:ThingPage" : "dsv:areElementsOf"

"td:Thing" <|-- "dsv:LinkDescription"
"td:Thing" <|-- "dsv:DirectoryDescription"
"td:Thing" --> "dsv:RegistrationInformation" : "dsv:hasRegistrationInfo"

show "dsv:ThingPage" attributes
show "dsv:RegistrationInformation" attributes
@enduml