@startuml
skin rose
skinparam defaultFontName "Noto Sans"
participant "Consumer" as Consumer
participant "Thing" as Thing

Consumer --> Thing : mDNS query\n"_wot._tcp.local PTR"
Thing ->  Consumer : mDNS resp.\n"_wot._tcp.local PTR lamp._wot._tcp.local"\n"lamp._wot._tcp.local SRV 1 0 80 lamp.local"\n"lamp._wot._tcp.local TXT td=/.well-known/wot;type=Thing"
Consumer -> Thing  : HTTP GET\n"http://lamp.local:80/.well-known/wot"
Thing ->  Consumer : HTTP 200 OK\nThing Description: '{"@context":...}'
@enduml