@startuml
skinparam defaultFontName "Noto Sans"
participant "Consumer" as Consumer
participant "Thing" as Thing

Consumer --> Thing : mDNS query\n"_thing._sub._wot._tcp.local PTR"
Thing ->  Consumer : mDNS resp.\n"PTR lamp._thing._sub._wot_tcp.local"
Consumer -> Thing  : mDNS query\n"lamp._thing._sub._wot._tcp.local ANY"
Thing ->  Consumer : mDNS resp.\n"SRV 1 0 80 lamp.local"\n"TXT td=/.well-known/wot-thing-description"
Consumer -> Thing  : HTTP GET\n"http://lamp.local:80/.well-known/wot-thing-description"
Thing ->  Consumer : HTTP 200 OK\nThing Description: '{"@context":...}'

@enduml