@startuml TDD Conceptual Class Diagram
class TDD as "Directory"
class TD as "td:Thing"
class DD as "tdd:DirectoryDescription"
class LD as "tdd:LinkDescription"
class RI as "tdd:RegistrationInfo"

/' relations '/
TDD "1" -- "many" TD: contains
TD *-right- RI
TD <|-- DD
TD <|-- LD

/' classes and notes '/
class TDD {

}
class TD {
    tdd:registration
    ...
}
note left: Thing Description (TD)
class RI {
    tdd:created {readOnly}
    tdd:expires {readOnly}
    tdd:id {readOnly}
    tdd:modified {readOnly}
    tdd:ttl
}
together {
    class DD {
        ...
    }
    note bottom: TD that describes\na Directory

    class LD {
        ...
    }
    note bottom: TD that describes\na reference to another TD
}

/' configurations '/
hide TDD members
' hide members
hide methods
@enduml