@startuml TDD Conceptual Class Diagram
class TDD as "TD Directory"

/' relations '/
TDD "1" -- "many" TD: contains
TD *-right- RegistrationInfo
TD <|-- DirectoryTD
TD <|-- LinkTD

/' classes and notes '/
class TDD {
    create(TD): ID
    list(page, page size)
    search(query)
    subscribe(event type, TD ID)
}
class TD {
    tdd:registration: RegistrationInfo
    ...
    create(ID, TD)
    read(ID): TD
    update(ID, TD)
    ' patch(ID, TD patch)
    delete(ID)
}
class RegistrationInfo {
    tdd:created
    tdd:modified
    tdd:ttl
    tdd:expires
}
together {
    class DirectoryTD <<TD>> {
        @type = tdd:Directory
        ...
    }
    note bottom: TD that describes a Directory

    class LinkTD <<TD>> {
        @type = tdd:Link
        ...
    }
    note bottom: TD that references a remote TD
}

/' configurations '/
hide TDD members
' hide members
hide methods
@enduml